-- Seed booking engines with known domain patterns
-- tier=1 means known/verified engine

INSERT INTO booking_engines (name, domains, tier) VALUES
('Cloudbeds', ARRAY['cloudbeds.com'], 1),
('Mews', ARRAY['mews.com', 'mews.li', 'app.mews.com', 'distributor.mews.com'], 1),
('SynXis / TravelClick', ARRAY['synxis.com', 'travelclick.com'], 1),
('BookingSuite / Booking.com', ARRAY['bookingsuite.com'], 1),
('Little Hotelier', ARRAY['littlehotelier.com'], 1),
('WebRezPro', ARRAY['webrezpro.com'], 1),
('InnRoad', ARRAY['innroad.com'], 1),
('ResNexus', ARRAY['resnexus.com'], 1),
('Newbook', ARRAY['newbook.cloud', 'newbooksoftware.com'], 1),
('RMS Cloud', ARRAY['rmscloud.com'], 1),
('RoomRaccoon', ARRAY['roomraccoon.com'], 1),
('SiteMinder', ARRAY['thebookingbutton.com', 'siteminder.com', 'direct-book'], 1),
('Sabre / CRS', ARRAY['sabre.com', 'crs.sabre.com'], 1),
('eZee', ARRAY['ezeeabsolute.com', 'ezeereservation.com', 'ezeetechnosys.com'], 1),
('RezTrip', ARRAY['reztrip.com'], 1),
('IHG', ARRAY['ihg.com'], 1),
('Marriott', ARRAY['marriott.com'], 1),
('Hilton', ARRAY['hilton.com'], 1),
('Vacatia', ARRAY['vacatia.com'], 1),
('JEHS / iPMS', ARRAY['ipms247.com', 'live.ipms247.com'], 1),
('Windsurfer CRS', ARRAY['windsurfercrs.com', 'res.windsurfercrs.com'], 1),
('ThinkReservations', ARRAY['thinkreservations.com', 'secure.thinkreservations.com'], 1),
('ASI Web Reservations', ARRAY['asiwebres.com', 'reservation.asiwebres.com'], 1),
('IQWebBook', ARRAY['iqwebbook.com', 'us01.iqwebbook.com'], 1),
('BookDirect', ARRAY['bookdirect.net', 'ococean.bookdirect.net'], 1),
('RezStream', ARRAY['rezstream.com', 'guest.rezstream.com'], 1),
('Reseze', ARRAY['reseze.net'], 1),
('WebRez', ARRAY['webrez.com', 'secure.webrez.com'], 1),
('IB Strategies', ARRAY['ibstrategies.com', 'secure.ibstrategies.com'], 1),
('ReservationKey', ARRAY['reservationkey.com', 'v2.reservationkey.com'], 1),
('FareHarbor', ARRAY['fareharbor.com'], 1),
('Firefly Reservations', ARRAY['fireflyreservations.com', 'app.fireflyreservations.com'], 1),
('Lodgify', ARRAY['lodgify.com', 'checkout.lodgify.com'], 1),
('eviivo', ARRAY['eviivo.com', 'via.eviivo.com'], 1),
('LuxuryRes', ARRAY['luxuryres.com'], 1),
('FreeToBook', ARRAY['freetobook.com', 'portal.freetobook.com'], 1),
('Checkfront', ARRAY['checkfront.com'], 1),
('Beds24', ARRAY['beds24.com'], 1),
('Hotelogix', ARRAY['hotelogix.com'], 1),
('inngenius', ARRAY['inngenius.com'], 1),
('Sirvoy', ARRAY['sirvoy.com'], 1),
('HotelRunner', ARRAY['hotelrunner.com'], 1),
('Amenitiz', ARRAY['amenitiz.io', 'amenitiz.com'], 1),
('Hostaway', ARRAY['hostaway.com'], 1),
('Guesty', ARRAY['guesty.com'], 1),
('Hospitable', ARRAY['hospitable.com'], 1),
('Lodgable', ARRAY['lodgable.com'], 1),
('HomHero', ARRAY['homhero.com.au', 'api.homhero.com.au', 'images.prod.homhero'], 1),
('Streamline', ARRAY['streamlinevrs.com', 'resortpro'], 1),
('Triptease', ARRAY['triptease.io', 'triptease.com', 'onboard.triptease'], 1),
('Yelp Reservations', ARRAY['yelp.com/reservations'], 1),
('Pegasus', ARRAY['pegasus.io', 'pegs.io'], 1),
('TravelTripper / Pegasus', ARRAY['traveltrip.com'], 1),
('OwnerReservations', ARRAY['ownerreservations.com', 'secure.ownerreservations.com'], 1),
('GuestRoomGenie', ARRAY['guestroomgenie.com', 'secure.guestroomgenie.com'], 1),
('Beyond Pricing', ARRAY['beyondpricing.com', 'beacon.beyondpricing.com'], 1),
('HotelKey', ARRAY['hotelkeyapp.com', 'booking.hotelkeyapp.com'], 1),
('Preno', ARRAY['prenohq.com', 'bookdirect.prenohq.com'], 1),
('Channel Manager AU', ARRAY['channelmanager.com.au', 'app.channelmanager.com.au'], 1),
('OfficialBookings', ARRAY['officialbookings.com'], 1),
('BookingMood', ARRAY['bookingmood.com', 'widget.bookingmood.com'], 1),
('Seekda / KUBE', ARRAY['seekda.com', 'kube.seekda.com', 'booking.seekda.com'], 1),
('StayDirectly', ARRAY['staydirectly.com'], 1),
('Rentrax', ARRAY['rentrax.io'], 1),
('Profitroom', ARRAY['profitroom.com', 'booking.profitroom.com'], 1),
('Avvio', ARRAY['avvio.com', 'booking.avvio.com'], 1),
('Net Affinity', ARRAY['netaffinity.com', 'booking.netaffinity.com'], 1),
('Simplotel', ARRAY['simplotel.com', 'booking.simplotel.com'], 1),
('Cubilis', ARRAY['cubilis.com', 'booking.cubilis.com'], 1),
('Cendyn', ARRAY['cendyn.com', 'booking.cendyn.com'], 1),
('BookLogic', ARRAY['booklogic.net', 'booking.booklogic.net'], 1),
('RateTiger', ARRAY['ratetiger.com', 'booking.ratetiger.com'], 1),
('D-Edge', ARRAY['d-edge.com', 'availpro.com', 'booking-ede.com'], 1),
('BookAssist', ARRAY['bookassist.com', 'booking.bookassist.org'], 1),
('GuestCentric', ARRAY['guestcentric.com', 'booking.guestcentric.com'], 1),
('Vertical Booking', ARRAY['verticalbooking.com', 'book.verticalbooking.com'], 1),
('Busy Rooms', ARRAY['busyrooms.com', 'booking.busyrooms.com'], 1),
('myHotel.io', ARRAY['myhotel.io'], 1),
('HotelSpider', ARRAY['hotelspider.com', 'be.hotelspider.com'], 1),
('Staah', ARRAY['staah.com', 'booking.staah.com'], 1),
('AxisRooms', ARRAY['axisrooms.com', 'booking.axisrooms.com'], 1),
('E4jConnect / VikBooking', ARRAY['e4jconnect.com', 'vikbooking.com'], 1),
('Apaleo', ARRAY['apaleo.com', 'app.apaleo.com'], 1),
('Clock PMS', ARRAY['clock-software.com', 'booking.clock-pms.com'], 1),
('Protel', ARRAY['protel.net', 'onity.com'], 1),
('Frontdesk Anywhere', ARRAY['frontdeskanywhere.com', 'booking.frontdeskanywhere.com'], 1),
('HotelTime', ARRAY['hoteltime.com'], 1),
('StayNTouch', ARRAY['stayntouch.com', 'rover.stayntouch.com'], 1),
('Oracle Opera', ARRAY['oracle.com/opera', 'opera-hotel.com'], 1),
('Infor HMS', ARRAY['infor.com'], 1),
('RoomCloud', ARRAY['roomcloud.net'], 1),
('Oaky', ARRAY['oaky.com'], 1),
('Revinate', ARRAY['revinate.com'], 1),
('TrustYou', ARRAY['trustyou.com'], 1),
('Escapia', ARRAY['escapia.com', 'homeaway.escapia.com'], 1),
('LiveRez', ARRAY['liverez.com', 'secure.liverez.com'], 1),
('Barefoot', ARRAY['barefoot.com', 'barefoot.systems'], 1),
('Track', ARRAY['trackhs.com', 'reserve.trackhs.com'], 1),
('Streamline VRS', ARRAY['streamlinevrs.com'], 1),
('iGMS', ARRAY['igms.com'], 1),
('Smoobu', ARRAY['smoobu.com', 'login.smoobu.com'], 1),
('Tokeet', ARRAY['tokeet.com'], 1),
('365Villas', ARRAY['365villas.com'], 1),
('Rentals United', ARRAY['rentalsunited.com'], 1),
('BookingSync', ARRAY['bookingsync.com'], 1),
('JANIIS', ARRAY['janiis.com', 'secure.janiis.com'], 1),
('Quibble', ARRAY['quibblerm.com'], 1),
('HiRUM', ARRAY['hirum.com.au', 'book.hirum.com.au'], 1),
('iBooked', ARRAY['ibooked.net.au', 'secure.ibooked.net.au'], 1),
('Seekom', ARRAY['seekom.com', 'book.seekom.com'], 1),
('ResPax', ARRAY['respax.com', 'app.respax.com'], 1),
('BookingCenter', ARRAY['bookingcenter.com'], 1),
('RezExpert', ARRAY['rezexpert.com'], 1),
('SuperControl', ARRAY['supercontrol.co.uk', 'members.supercontrol.co.uk'], 1),
('Anytime Booking', ARRAY['anytimebooking.eu', 'anytimebooking.co.uk'], 1),
('Elina PMS', ARRAY['elinapms.com'], 1),
('Guestline', ARRAY['guestline.com', 'booking.guestline.com'], 1),
('Nonius', ARRAY['nonius.com'], 1),
('Visual Matrix', ARRAY['visualmatrix.com', 'pms.visualmatrix.com'], 1),
('AutoClerk', ARRAY['autoclerk.com'], 1),
('MSI', ARRAY['msisolutions.com'], 1),
('SkyTouch', ARRAY['skytouch.com', 'pms.skytouch.com'], 1),
('RoomKeyPMS', ARRAY['roomkeypms.com', 'secure.roomkeypms.com'], 1)
ON CONFLICT (name) DO UPDATE SET
    domains = EXCLUDED.domains,
    tier = EXCLUDED.tier;
